essential.defaults.loom=0
essential.defaults.loom.fabric-loader=net.fabricmc:fabric-loader:0.19.5
kotlin.stdlib.default.dependency=false
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.parallel.threads=128
org.gradle.jvmargs=-Xmx16G
org.gradle.caching=true
minecraftVersion=11202
version=1.5.0.1
